# Change these first
owner: rholak
repo: upptime

sites:
  - name: This Repo
    url: https://github.com/rholak/upptime/
  - name: Status Page
    url: https://rholak.github.io/upptime/
  - name: BOS
    url: $URL_BOS
  - name: BOS2
    url: $URL_BOS2
  - name: Altor
    url: $URL_PUBLIC_SITE
  - name: Goog
    url: https://google.com/
  - name: Google DNS 1
    check: "tcp-ping"
    url: 8.8.4.4
    port: 53
  - name: Google DNS 2
    check: "tcp-ping"
    url: 8.8.8.8
    port: 53

assignees:
  - rholak

status-website:
  baseUrl: /upptime
  name: Your Time is Up
  theme: ocean
  navbar:
  - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
