# Change these first
owner: rholak
repo: upptime

sites:
  - name: BOS
    url: https://altor-bos.com/
  - name: Altor
    url: https://altorntl.com/
  - name: Goog
    url: https://google.com/

status-website:
  baseUrl: /upptime
  name: Time is Up


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
